export const COUNTER_REQUEST_UP = "COUNTER_REQUEST_UP";
export const COUNTER_REQUEST_DOWN = "COUNTER_REQUEST_DOWN";

export const COUNTER_ASYNC_UP = "COUNTER_ASYNC_UP";
export const COUNTER_ASYNC_DOWN = "COUNTER_ASYNC_DOWN";